# Generated by Django 4.2 on 2023-04-05 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('empid', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('designation', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('gender', models.CharField(max_length=255)),
                ('eligible_leave', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('Is_employee', models.CharField(max_length=255)),
                ('reporting_to', models.CharField(max_length=255)),
            ],
        ),
    ]
