# Generated by Django 4.2 on 2023-04-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empdetails',
            options={'verbose_name_plural': 'EmpDetails'},
        ),
    ]
