# Generated by Django 4.2 on 2023-04-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsdetails', '0002_alter_empdetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empdetails',
            options={},
        ),
    ]
