# Generated by Django 4.2 on 2023-04-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsdetails', '0003_alter_empdetails_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='designation',
            field=models.CharField(max_length=255),
        ),
    ]
